# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {C:/Vivado file/Pacman/Pacman/Pacman.cache/wt} [current_project]
set_property parent.project_path {C:/Vivado file/Pacman/Pacman/Pacman.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
read_verilog -library xil_defaultlib {
  {C:/Vivado file/Pacman/Pacman/Pacman.srcs/sources_1/new/gameover_rom.v}
  {C:/Vivado file/Pacman/Pacman/Pacman.srcs/sources_1/new/walls_rom.v}
  {C:/Vivado file/Pacman/Pacman/Pacman.srcs/sources_1/new/Star_rom.v}
  {C:/Vivado file/Pacman/Pacman/Pacman.srcs/sources_1/new/red_ghost_rom.v}
  {C:/Vivado file/Pacman/Pacman/Pacman.srcs/sources_1/new/Hearts_rom.v}
  {C:/Vivado file/Pacman/Pacman/Pacman.srcs/sources_1/new/Blue_Ghost_rom.v}
  {C:/Vivado file/Pacman/Pacman/Pacman.srcs/sources_1/new/Pacman_rom.v}
  {C:/Vivado file/Pacman/Pacman/Pacman.srcs/sources_1/new/Pacman_Ghost_rom.v}
  {C:/Vivado file/Pacman/Pacman/Pacman.srcs/sources_1/new/gameover_display.v}
  {C:/Vivado file/Pacman/Pacman/Pacman.srcs/sources_1/new/Walls.v}
  {C:/Vivado file/Pacman/Pacman/Pacman.srcs/sources_1/new/vga_sync.v}
  {C:/Vivado file/Pacman/Pacman/Pacman.srcs/sources_1/new/Star.v}
  {C:/Vivado file/Pacman/Pacman/Pacman.srcs/sources_1/new/Hearts_display.v}
  {C:/Vivado file/Pacman/Pacman/Pacman.srcs/sources_1/new/Ghost_Red.v}
  {C:/Vivado file/Pacman/Pacman/Pacman.srcs/sources_1/new/Ghost_Blue.v}
  {C:/Vivado file/Pacman/Pacman/Pacman.srcs/sources_1/new/Game_state_machine.v}
  {C:/Vivado file/Pacman/Pacman/Pacman.srcs/sources_1/new/Check_collision.v}
  {C:/Vivado file/Pacman/Pacman/Pacman.srcs/sources_1/new/Background_rom.v}
  {C:/Vivado file/Pacman/Pacman/Pacman.srcs/sources_1/new/Pacman_control.v}
  {C:/Vivado file/Pacman/Pacman/Pacman.srcs/sources_1/new/top_module.v}
}
read_xdc {{C:/Vivado file/Basys-3-Master.xdc}}
set_property used_in_implementation false [get_files {{C:/Vivado file/Basys-3-Master.xdc}}]

synth_design -top top_module -part xc7a35tcpg236-1
write_checkpoint -noxdef top_module.dcp
catch { report_utilization -file top_module_utilization_synth.rpt -pb top_module_utilization_synth.pb }
